package c5;

/* compiled from: r8-map-id-55c51131a4e3e5b800077d6b571ddc9a5a11ae13728b5823d570600aeb3bdcdf */
/* loaded from: classes.dex */
public abstract class g0 {
    public static final h a;
    public static final h b;
    public static final h c;
    public static final h d;
    public static final h e;
    public static final h f;
    public static final h g;
    public static final h h;
    public static final h i;
    public static final h j;
    public static final h k;
    public static final h l;
    public static final h m;
    public static final h n;
    public static final h o;
    public static final h p;

    static {
        c3.a a2 = h.a();
        a2.b = 3;
        a2.a = "Google Play In-app Billing API version is less than 3";
        a2.a();
        c3.a a10 = h.a();
        a10.b = 3;
        a10.a = "Google Play In-app Billing API version is less than 9";
        a10.a();
        c3.a a11 = h.a();
        a11.b = 3;
        a11.a = "Billing service unavailable on device.";
        a = a11.a();
        c3.a a12 = h.a();
        a12.b = 2;
        a12.a = "Billing service unavailable on device.";
        b = a12.a();
        c3.a a13 = h.a();
        a13.b = 5;
        a13.a = "Client is already in the process of connecting to billing service.";
        c = a13.a();
        c3.a a14 = h.a();
        a14.b = 5;
        a14.a = "The list of SKUs can't be empty.";
        a14.a();
        c3.a a15 = h.a();
        a15.b = 5;
        a15.a = "SKU type can't be empty.";
        a15.a();
        c3.a a16 = h.a();
        a16.b = 5;
        a16.a = "Product type can't be empty.";
        d = a16.a();
        c3.a a17 = h.a();
        a17.b = -2;
        a17.a = "Client does not support extra params.";
        e = a17.a();
        c3.a a18 = h.a();
        a18.b = 5;
        a18.a = "Invalid purchase token.";
        a18.a();
        c3.a a19 = h.a();
        a19.b = 6;
        a19.a = "An internal error occurred.";
        f = a19.a();
        c3.a a20 = h.a();
        a20.b = 5;
        a20.a = "SKU can't be null.";
        a20.a();
        c3.a a21 = h.a();
        a21.b = 0;
        g = a21.a();
        c3.a a22 = h.a();
        a22.b = -1;
        a22.a = "Service connection is disconnected.";
        h = a22.a();
        c3.a a23 = h.a();
        a23.b = 2;
        a23.a = "Timeout communicating with service.";
        i = a23.a();
        c3.a a24 = h.a();
        a24.b = -2;
        a24.a = "Client does not support subscriptions.";
        j = a24.a();
        c3.a a25 = h.a();
        a25.b = -2;
        a25.a = "Client does not support subscriptions update.";
        a25.a();
        c3.a a26 = h.a();
        a26.b = -2;
        a26.a = "Client does not support get purchase history.";
        a26.a();
        c3.a a27 = h.a();
        a27.b = -2;
        a27.a = "Client does not support price change confirmation.";
        a27.a();
        c3.a a28 = h.a();
        a28.b = -2;
        a28.a = "Play Store version installed does not support cross selling products.";
        a28.a();
        c3.a a29 = h.a();
        a29.b = -2;
        a29.a = "Client does not support multi-item purchases.";
        k = a29.a();
        c3.a a30 = h.a();
        a30.b = -2;
        a30.a = "Client does not support offer_id_token.";
        l = a30.a();
        c3.a a31 = h.a();
        a31.b = -2;
        a31.a = "Client does not support ProductDetails.";
        m = a31.a();
        c3.a a32 = h.a();
        a32.b = -2;
        a32.a = "Client does not support in-app messages.";
        a32.a();
        c3.a a33 = h.a();
        a33.b = -2;
        a33.a = "Client does not support user choice billing.";
        a33.a();
        c3.a a34 = h.a();
        a34.b = -2;
        a34.a = "Play Store version installed does not support external offer.";
        a34.a();
        c3.a a35 = h.a();
        a35.b = -2;
        a35.a = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        a35.a();
        c3.a a36 = h.a();
        a36.b = -2;
        a36.a = "Play Store version installed does not support querying AutoPay plan purchase.";
        a36.a();
        c3.a a37 = h.a();
        a37.b = -2;
        a37.a = "Play Store version installed does not support including suspended subscriptions.";
        a37.a();
        c3.a a38 = h.a();
        a38.b = 5;
        a38.a = "Unknown feature";
        a38.a();
        c3.a a39 = h.a();
        a39.b = -2;
        a39.a = "Play Store version installed does not support get billing config.";
        a39.a();
        c3.a a40 = h.a();
        a40.b = -2;
        a40.a = "Query product details with serialized docid is not supported.";
        a40.a();
        c3.a a41 = h.a();
        a41.b = -2;
        a41.a = "Play Store version installed does not support launching external offer flow.";
        a41.a();
        c3.a a42 = h.a();
        a42.b = 4;
        a42.a = "Item is unavailable for purchase.";
        n = a42.a();
        c3.a a43 = h.a();
        a43.b = -2;
        a43.a = "Query product details with developer specified account is not supported.";
        a43.a();
        c3.a a44 = h.a();
        a44.b = -2;
        a44.a = "Play Store version installed does not support alternative billing only.";
        a44.a();
        c3.a a45 = h.a();
        a45.b = 5;
        a45.a = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        o = a45.a();
        c3.a a46 = h.a();
        a46.b = 6;
        a46.a = "An error occurred while retrieving billing override.";
        p = a46.a();
        c3.a a47 = h.a();
        a47.b = -2;
        a47.a = "Play Store version installed does not support the provided billing program.";
        a47.a();
    }

    public static h a(int i10, String str) {
        c3.a a2 = h.a();
        a2.b = i10;
        a2.a = str;
        return a2.a();
    }
}
