package n2;

/* compiled from: r8-map-id-11b2057e7e9050c40bb40722946bba2b5eb90c231d630684b08af6cb92d5aac3 */
/* loaded from: classes.dex */
public abstract class b0 {
    public static final g a;
    public static final g b;
    public static final g c;
    public static final g d;
    public static final g e;
    public static final g f;
    public static final g g;
    public static final g h;
    public static final g i;
    public static final g j;
    public static final g k;
    public static final g l;
    public static final g m;
    public static final g n;
    public static final g o;
    public static final g p;

    static {
        j3.a a2 = g.a();
        a2.a = 3;
        a2.c = "Google Play In-app Billing API version is less than 3";
        a2.a();
        j3.a a3 = g.a();
        a3.a = 3;
        a3.c = "Google Play In-app Billing API version is less than 9";
        a3.a();
        j3.a a10 = g.a();
        a10.a = 3;
        a10.c = "Billing service unavailable on device.";
        a = a10.a();
        j3.a a11 = g.a();
        a11.a = 2;
        a11.c = "Billing service unavailable on device.";
        b = a11.a();
        j3.a a12 = g.a();
        a12.a = 5;
        a12.c = "Client is already in the process of connecting to billing service.";
        c = a12.a();
        j3.a a13 = g.a();
        a13.a = 5;
        a13.c = "The list of SKUs can't be empty.";
        a13.a();
        j3.a a14 = g.a();
        a14.a = 5;
        a14.c = "SKU type can't be empty.";
        a14.a();
        j3.a a15 = g.a();
        a15.a = 5;
        a15.c = "Product type can't be empty.";
        d = a15.a();
        j3.a a16 = g.a();
        a16.a = -2;
        a16.c = "Client does not support extra params.";
        e = a16.a();
        j3.a a17 = g.a();
        a17.a = 5;
        a17.c = "Invalid purchase token.";
        a17.a();
        j3.a a18 = g.a();
        a18.a = 6;
        a18.c = "An internal error occurred.";
        f = a18.a();
        j3.a a19 = g.a();
        a19.a = 5;
        a19.c = "SKU can't be null.";
        a19.a();
        j3.a a20 = g.a();
        a20.a = 0;
        g = a20.a();
        j3.a a21 = g.a();
        a21.a = -1;
        a21.c = "Service connection is disconnected.";
        h = a21.a();
        j3.a a22 = g.a();
        a22.a = 2;
        a22.c = "Timeout communicating with service.";
        i = a22.a();
        j3.a a23 = g.a();
        a23.a = -2;
        a23.c = "Client does not support subscriptions.";
        j = a23.a();
        j3.a a24 = g.a();
        a24.a = -2;
        a24.c = "Client does not support subscriptions update.";
        a24.a();
        j3.a a25 = g.a();
        a25.a = -2;
        a25.c = "Client does not support get purchase history.";
        a25.a();
        j3.a a26 = g.a();
        a26.a = -2;
        a26.c = "Client does not support price change confirmation.";
        a26.a();
        j3.a a27 = g.a();
        a27.a = -2;
        a27.c = "Play Store version installed does not support cross selling products.";
        a27.a();
        j3.a a28 = g.a();
        a28.a = -2;
        a28.c = "Client does not support multi-item purchases.";
        k = a28.a();
        j3.a a29 = g.a();
        a29.a = -2;
        a29.c = "Client does not support offer_id_token.";
        l = a29.a();
        j3.a a30 = g.a();
        a30.a = -2;
        a30.c = "Client does not support ProductDetails.";
        m = a30.a();
        j3.a a31 = g.a();
        a31.a = -2;
        a31.c = "Client does not support in-app messages.";
        a31.a();
        j3.a a32 = g.a();
        a32.a = -2;
        a32.c = "Client does not support user choice billing.";
        a32.a();
        j3.a a33 = g.a();
        a33.a = -2;
        a33.c = "Play Store version installed does not support external offer.";
        a33.a();
        j3.a a34 = g.a();
        a34.a = -2;
        a34.c = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        a34.a();
        j3.a a35 = g.a();
        a35.a = -2;
        a35.c = "Play Store version installed does not support querying AutoPay plan purchase.";
        a35.a();
        j3.a a36 = g.a();
        a36.a = -2;
        a36.c = "Play Store version installed does not support including suspended subscriptions.";
        a36.a();
        j3.a a37 = g.a();
        a37.a = 5;
        a37.c = "Unknown feature";
        a37.a();
        j3.a a38 = g.a();
        a38.a = -2;
        a38.c = "Play Store version installed does not support get billing config.";
        a38.a();
        j3.a a39 = g.a();
        a39.a = -2;
        a39.c = "Query product details with serialized docid is not supported.";
        a39.a();
        j3.a a40 = g.a();
        a40.a = -2;
        a40.c = "Play Store version installed does not support launching external offer flow.";
        a40.a();
        j3.a a41 = g.a();
        a41.a = 4;
        a41.c = "Item is unavailable for purchase.";
        n = a41.a();
        j3.a a42 = g.a();
        a42.a = -2;
        a42.c = "Query product details with developer specified account is not supported.";
        a42.a();
        j3.a a43 = g.a();
        a43.a = -2;
        a43.c = "Play Store version installed does not support alternative billing only.";
        a43.a();
        j3.a a44 = g.a();
        a44.a = 5;
        a44.c = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        o = a44.a();
        j3.a a45 = g.a();
        a45.a = 6;
        a45.c = "An error occurred while retrieving billing override.";
        p = a45.a();
        j3.a a46 = g.a();
        a46.a = -2;
        a46.c = "Play Store version installed does not support the provided billing program.";
        a46.a();
    }

    public static g a(int i9, String str) {
        j3.a a2 = g.a();
        a2.a = i9;
        a2.c = str;
        return a2.a();
    }
}
