package p2;

/* compiled from: r8-map-id-33f3ee7b3837766f245c82aac5a618a539713405f9dc265162d35c247069ed49 */
/* loaded from: classes.dex */
public abstract class b0 {
    public static final h a;
    public static final h b;
    public static final h c;
    public static final h d;
    public static final h e;
    public static final h f;
    public static final h g;
    public static final h h;
    public static final h i;
    public static final h j;
    public static final h k;
    public static final h l;
    public static final h m;
    public static final h n;
    public static final h o;
    public static final h p;

    static {
        g a2 = h.a();
        a2.a = 3;
        a2.c = "Google Play In-app Billing API version is less than 3";
        a2.e();
        g a10 = h.a();
        a10.a = 3;
        a10.c = "Google Play In-app Billing API version is less than 9";
        a10.e();
        g a11 = h.a();
        a11.a = 3;
        a11.c = "Billing service unavailable on device.";
        a = a11.e();
        g a12 = h.a();
        a12.a = 2;
        a12.c = "Billing service unavailable on device.";
        b = a12.e();
        g a13 = h.a();
        a13.a = 5;
        a13.c = "Client is already in the process of connecting to billing service.";
        c = a13.e();
        g a14 = h.a();
        a14.a = 5;
        a14.c = "The list of SKUs can't be empty.";
        a14.e();
        g a15 = h.a();
        a15.a = 5;
        a15.c = "SKU type can't be empty.";
        a15.e();
        g a16 = h.a();
        a16.a = 5;
        a16.c = "Product type can't be empty.";
        d = a16.e();
        g a17 = h.a();
        a17.a = -2;
        a17.c = "Client does not support extra params.";
        e = a17.e();
        g a18 = h.a();
        a18.a = 5;
        a18.c = "Invalid purchase token.";
        a18.e();
        g a19 = h.a();
        a19.a = 6;
        a19.c = "An internal error occurred.";
        f = a19.e();
        g a20 = h.a();
        a20.a = 5;
        a20.c = "SKU can't be null.";
        a20.e();
        g a21 = h.a();
        a21.a = 0;
        g = a21.e();
        g a22 = h.a();
        a22.a = -1;
        a22.c = "Service connection is disconnected.";
        h = a22.e();
        g a23 = h.a();
        a23.a = 2;
        a23.c = "Timeout communicating with service.";
        i = a23.e();
        g a24 = h.a();
        a24.a = -2;
        a24.c = "Client does not support subscriptions.";
        j = a24.e();
        g a25 = h.a();
        a25.a = -2;
        a25.c = "Client does not support subscriptions update.";
        a25.e();
        g a26 = h.a();
        a26.a = -2;
        a26.c = "Client does not support get purchase history.";
        a26.e();
        g a27 = h.a();
        a27.a = -2;
        a27.c = "Client does not support price change confirmation.";
        a27.e();
        g a28 = h.a();
        a28.a = -2;
        a28.c = "Play Store version installed does not support cross selling products.";
        a28.e();
        g a29 = h.a();
        a29.a = -2;
        a29.c = "Client does not support multi-item purchases.";
        k = a29.e();
        g a30 = h.a();
        a30.a = -2;
        a30.c = "Client does not support offer_id_token.";
        l = a30.e();
        g a31 = h.a();
        a31.a = -2;
        a31.c = "Client does not support ProductDetails.";
        m = a31.e();
        g a32 = h.a();
        a32.a = -2;
        a32.c = "Client does not support in-app messages.";
        a32.e();
        g a33 = h.a();
        a33.a = -2;
        a33.c = "Client does not support user choice billing.";
        a33.e();
        g a34 = h.a();
        a34.a = -2;
        a34.c = "Play Store version installed does not support external offer.";
        a34.e();
        g a35 = h.a();
        a35.a = -2;
        a35.c = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        a35.e();
        g a36 = h.a();
        a36.a = -2;
        a36.c = "Play Store version installed does not support querying AutoPay plan purchase.";
        a36.e();
        g a37 = h.a();
        a37.a = -2;
        a37.c = "Play Store version installed does not support including suspended subscriptions.";
        a37.e();
        g a38 = h.a();
        a38.a = 5;
        a38.c = "Unknown feature";
        a38.e();
        g a39 = h.a();
        a39.a = -2;
        a39.c = "Play Store version installed does not support get billing config.";
        a39.e();
        g a40 = h.a();
        a40.a = -2;
        a40.c = "Query product details with serialized docid is not supported.";
        a40.e();
        g a41 = h.a();
        a41.a = -2;
        a41.c = "Play Store version installed does not support launching external offer flow.";
        a41.e();
        g a42 = h.a();
        a42.a = 4;
        a42.c = "Item is unavailable for purchase.";
        n = a42.e();
        g a43 = h.a();
        a43.a = -2;
        a43.c = "Query product details with developer specified account is not supported.";
        a43.e();
        g a44 = h.a();
        a44.a = -2;
        a44.c = "Play Store version installed does not support alternative billing only.";
        a44.e();
        g a45 = h.a();
        a45.a = 5;
        a45.c = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        o = a45.e();
        g a46 = h.a();
        a46.a = 6;
        a46.c = "An error occurred while retrieving billing override.";
        p = a46.e();
        g a47 = h.a();
        a47.a = -2;
        a47.c = "Play Store version installed does not support the provided billing program.";
        a47.e();
    }

    public static h a(int i10, String str) {
        g a2 = h.a();
        a2.a = i10;
        a2.c = str;
        return a2.e();
    }
}
