package w7;

/* compiled from: r8-map-id-55c51131a4e3e5b800077d6b571ddc9a5a11ae13728b5823d570600aeb3bdcdf */
/* loaded from: classes.dex */
public final class g3 implements ia.d {
    public static final g3 a = new g3();
    public static final ia.c b = new ia.c("systemInfo", hc.b.p(w.f.i(d.class, new a(1))));
    public static final ia.c c = new ia.c("eventName", hc.b.p(w.f.i(d.class, new a(2))));
    public static final ia.c d = new ia.c("isThickClient", hc.b.p(w.f.i(d.class, new a(37))));
    public static final ia.c e = new ia.c("clientType", hc.b.p(w.f.i(d.class, new a(61))));
    public static final ia.c f = new ia.c("modelDownloadLogEvent", hc.b.p(w.f.i(d.class, new a(3))));
    public static final ia.c g = new ia.c("customModelLoadLogEvent", hc.b.p(w.f.i(d.class, new a(20))));
    public static final ia.c h = new ia.c("customModelInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(4))));
    public static final ia.c i = new ia.c("customModelCreateLogEvent", hc.b.p(w.f.i(d.class, new a(29))));
    public static final ia.c j = new ia.c("onDeviceFaceDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(5))));
    public static final ia.c k = new ia.c("onDeviceFaceLoadLogEvent", hc.b.p(w.f.i(d.class, new a(59))));
    public static final ia.c l = new ia.c("onDeviceTextDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(6))));
    public static final ia.c m = new ia.c("onDeviceTextDetectionLoadLogEvent", hc.b.p(w.f.i(d.class, new a(79))));
    public static final ia.c n = new ia.c("onDeviceBarcodeDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(7))));
    public static final ia.c o = new ia.c("onDeviceBarcodeLoadLogEvent", hc.b.p(w.f.i(d.class, new a(58))));
    public static final ia.c p = new ia.c("onDeviceImageLabelCreateLogEvent", hc.b.p(w.f.i(d.class, new a(48))));
    public static final ia.c q = new ia.c("onDeviceImageLabelLoadLogEvent", hc.b.p(w.f.i(d.class, new a(49))));
    public static final ia.c r = new ia.c("onDeviceImageLabelDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(18))));
    public static final ia.c s = new ia.c("onDeviceObjectCreateLogEvent", hc.b.p(w.f.i(d.class, new a(26))));
    public static final ia.c t = new ia.c("onDeviceObjectLoadLogEvent", hc.b.p(w.f.i(d.class, new a(27))));
    public static final ia.c u = new ia.c("onDeviceObjectInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(28))));
    public static final ia.c v = new ia.c("onDevicePoseDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(44))));
    public static final ia.c w = new ia.c("onDeviceSegmentationLogEvent", hc.b.p(w.f.i(d.class, new a(45))));
    public static final ia.c x = new ia.c("onDeviceSmartReplyLogEvent", hc.b.p(w.f.i(d.class, new a(19))));
    public static final ia.c y = new ia.c("onDeviceLanguageIdentificationLogEvent", hc.b.p(w.f.i(d.class, new a(21))));
    public static final ia.c z = new ia.c("onDeviceTranslationLogEvent", hc.b.p(w.f.i(d.class, new a(22))));
    public static final ia.c A = new ia.c("cloudFaceDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(8))));
    public static final ia.c B = new ia.c("cloudCropHintDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(9))));
    public static final ia.c C = new ia.c("cloudDocumentTextDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(10))));
    public static final ia.c D = new ia.c("cloudImagePropertiesDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(11))));
    public static final ia.c E = new ia.c("cloudImageLabelDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(12))));
    public static final ia.c F = new ia.c("cloudLandmarkDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(13))));
    public static final ia.c G = new ia.c("cloudLogoDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(14))));
    public static final ia.c H = new ia.c("cloudSafeSearchDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(15))));
    public static final ia.c I = new ia.c("cloudTextDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(16))));
    public static final ia.c J = new ia.c("cloudWebSearchDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(17))));
    public static final ia.c K = new ia.c("automlImageLabelingCreateLogEvent", hc.b.p(w.f.i(d.class, new a(23))));
    public static final ia.c L = new ia.c("automlImageLabelingLoadLogEvent", hc.b.p(w.f.i(d.class, new a(24))));
    public static final ia.c M = new ia.c("automlImageLabelingInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(25))));
    public static final ia.c N = new ia.c("isModelDownloadedLogEvent", hc.b.p(w.f.i(d.class, new a(39))));
    public static final ia.c O = new ia.c("deleteModelLogEvent", hc.b.p(w.f.i(d.class, new a(40))));
    public static final ia.c P = new ia.c("aggregatedAutomlImageLabelingInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(30))));
    public static final ia.c Q = new ia.c("aggregatedCustomModelInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(31))));
    public static final ia.c R = new ia.c("aggregatedOnDeviceFaceDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(32))));
    public static final ia.c S = new ia.c("aggregatedOnDeviceBarcodeDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(33))));
    public static final ia.c T = new ia.c("aggregatedOnDeviceImageLabelDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(34))));
    public static final ia.c U = new ia.c("aggregatedOnDeviceObjectInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(35))));
    public static final ia.c V = new ia.c("aggregatedOnDeviceTextDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(36))));
    public static final ia.c W = new ia.c("aggregatedOnDevicePoseDetectionLogEvent", hc.b.p(w.f.i(d.class, new a(46))));
    public static final ia.c X = new ia.c("aggregatedOnDeviceSegmentationLogEvent", hc.b.p(w.f.i(d.class, new a(47))));
    public static final ia.c Y = new ia.c("pipelineAccelerationInferenceEvents", hc.b.p(w.f.i(d.class, new a(69))));
    public static final ia.c Z = new ia.c("remoteConfigLogEvent", hc.b.p(w.f.i(d.class, new a(42))));
    public static final ia.c a0 = new ia.c("inputImageConstructionLogEvent", hc.b.p(w.f.i(d.class, new a(50))));
    public static final ia.c b0 = new ia.c("leakedHandleEvent", hc.b.p(w.f.i(d.class, new a(51))));
    public static final ia.c c0 = new ia.c("cameraSourceLogEvent", hc.b.p(w.f.i(d.class, new a(52))));
    public static final ia.c d0 = new ia.c("imageLabelOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(53))));
    public static final ia.c e0 = new ia.c("languageIdentificationOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(54))));
    public static final ia.c f0 = new ia.c("faceDetectionOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(60))));
    public static final ia.c g0 = new ia.c("documentDetectionOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(85))));
    public static final ia.c h0 = new ia.c("documentCroppingOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(86))));
    public static final ia.c i0 = new ia.c("documentEnhancementOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(87))));
    public static final ia.c j0 = new ia.c("nlClassifierOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(55))));
    public static final ia.c k0 = new ia.c("nlClassifierClientLibraryLogEvent", hc.b.p(w.f.i(d.class, new a(56))));
    public static final ia.c l0 = new ia.c("accelerationAllowlistLogEvent", hc.b.p(w.f.i(d.class, new a(57))));
    public static final ia.c m0 = new ia.c("toxicityDetectionCreateEvent", hc.b.p(w.f.i(d.class, new a(62))));
    public static final ia.c n0 = new ia.c("toxicityDetectionLoadEvent", hc.b.p(w.f.i(d.class, new a(63))));
    public static final ia.c o0 = new ia.c("toxicityDetectionInferenceEvent", hc.b.p(w.f.i(d.class, new a(64))));
    public static final ia.c p0 = new ia.c("barcodeDetectionOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(65))));
    public static final ia.c q0 = new ia.c("customImageLabelOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(66))));
    public static final ia.c r0 = new ia.c("codeScannerScanApiEvent", hc.b.p(w.f.i(d.class, new a(67))));
    public static final ia.c s0 = new ia.c("codeScannerOptionalModuleEvent", hc.b.p(w.f.i(d.class, new a(68))));
    public static final ia.c t0 = new ia.c("onDeviceExplicitContentCreateLogEvent", hc.b.p(w.f.i(d.class, new a(70))));
    public static final ia.c u0 = new ia.c("onDeviceExplicitContentLoadLogEvent", hc.b.p(w.f.i(d.class, new a(71))));
    public static final ia.c v0 = new ia.c("onDeviceExplicitContentInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(72))));
    public static final ia.c w0 = new ia.c("aggregatedOnDeviceExplicitContentLogEvent", hc.b.p(w.f.i(d.class, new a(73))));
    public static final ia.c x0 = new ia.c("onDeviceFaceMeshCreateLogEvent", hc.b.p(w.f.i(d.class, new a(74))));
    public static final ia.c y0 = new ia.c("onDeviceFaceMeshLoadLogEvent", hc.b.p(w.f.i(d.class, new a(75))));
    public static final ia.c z0 = new ia.c("onDeviceFaceMeshLogEvent", hc.b.p(w.f.i(d.class, new a(76))));
    public static final ia.c A0 = new ia.c("aggregatedOnDeviceFaceMeshLogEvent", hc.b.p(w.f.i(d.class, new a(77))));
    public static final ia.c B0 = new ia.c("smartReplyOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(78))));
    public static final ia.c C0 = new ia.c("textDetectionOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(80))));
    public static final ia.c D0 = new ia.c("onDeviceImageQualityAnalysisCreateLogEvent", hc.b.p(w.f.i(d.class, new a(81))));
    public static final ia.c E0 = new ia.c("onDeviceImageQualityAnalysisLoadLogEvent", hc.b.p(w.f.i(d.class, new a(82))));
    public static final ia.c F0 = new ia.c("onDeviceImageQualityAnalysisLogEvent", hc.b.p(w.f.i(d.class, new a(83))));
    public static final ia.c G0 = new ia.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", hc.b.p(w.f.i(d.class, new a(84))));
    public static final ia.c H0 = new ia.c("imageQualityAnalysisOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(88))));
    public static final ia.c I0 = new ia.c("imageCaptioningOptionalModuleLogEvent", hc.b.p(w.f.i(d.class, new a(89))));
    public static final ia.c J0 = new ia.c("onDeviceImageCaptioningCreateLogEvent", hc.b.p(w.f.i(d.class, new a(90))));
    public static final ia.c K0 = new ia.c("onDeviceImageCaptioningLoadLogEvent", hc.b.p(w.f.i(d.class, new a(91))));
    public static final ia.c L0 = new ia.c("onDeviceImageCaptioningInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(92))));
    public static final ia.c M0 = new ia.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", hc.b.p(w.f.i(d.class, new a(93))));

    @Override // ia.a
    public final void a(Object obj, Object obj2) {
        k7 k7Var = (k7) obj;
        ia.e eVar = (ia.e) obj2;
        eVar.a(b, k7Var.a);
        eVar.a(c, k7Var.b);
        eVar.a(d, null);
        eVar.a(e, null);
        eVar.a(f, null);
        eVar.a(g, null);
        eVar.a(h, null);
        eVar.a(i, null);
        eVar.a(j, null);
        eVar.a(k, null);
        eVar.a(l, null);
        eVar.a(m, null);
        eVar.a(n, null);
        eVar.a(o, null);
        eVar.a(p, null);
        eVar.a(q, null);
        eVar.a(r, null);
        eVar.a(s, null);
        eVar.a(t, null);
        eVar.a(u, null);
        eVar.a(v, null);
        eVar.a(w, null);
        eVar.a(x, null);
        eVar.a(y, null);
        eVar.a(z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(a0, k7Var.c);
        eVar.a(b0, null);
        eVar.a(c0, null);
        eVar.a(d0, null);
        eVar.a(e0, null);
        eVar.a(f0, null);
        eVar.a(g0, null);
        eVar.a(h0, null);
        eVar.a(i0, null);
        eVar.a(j0, null);
        eVar.a(k0, null);
        eVar.a(l0, null);
        eVar.a(m0, null);
        eVar.a(n0, null);
        eVar.a(o0, null);
        eVar.a(p0, null);
        eVar.a(q0, null);
        eVar.a(r0, null);
        eVar.a(s0, null);
        eVar.a(t0, null);
        eVar.a(u0, null);
        eVar.a(v0, null);
        eVar.a(w0, null);
        eVar.a(x0, null);
        eVar.a(y0, null);
        eVar.a(z0, null);
        eVar.a(A0, null);
        eVar.a(B0, null);
        eVar.a(C0, null);
        eVar.a(D0, null);
        eVar.a(E0, null);
        eVar.a(F0, null);
        eVar.a(G0, null);
        eVar.a(H0, null);
        eVar.a(I0, null);
        eVar.a(J0, null);
        eVar.a(K0, null);
        eVar.a(L0, null);
        eVar.a(M0, null);
    }
}
