package i7;

/* compiled from: r8-map-id-818410c928e26989539d9c43666f59979e404aa44db880373fadfbe90836d366 */
/* loaded from: classes.dex */
public final class z3 implements r9.d {
    public static final z3 a = new z3();
    public static final r9.c b = new r9.c("systemInfo", s3.c.h(i0.a.r(h0.class, new e0(1))));
    public static final r9.c c = new r9.c("eventName", s3.c.h(i0.a.r(h0.class, new e0(2))));
    public static final r9.c d = new r9.c("isThickClient", s3.c.h(i0.a.r(h0.class, new e0(37))));
    public static final r9.c e = new r9.c("clientType", s3.c.h(i0.a.r(h0.class, new e0(61))));
    public static final r9.c f = new r9.c("modelDownloadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(3))));
    public static final r9.c g = new r9.c("customModelLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(20))));
    public static final r9.c h = new r9.c("customModelInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(4))));
    public static final r9.c i = new r9.c("customModelCreateLogEvent", s3.c.h(i0.a.r(h0.class, new e0(29))));
    public static final r9.c j = new r9.c("onDeviceFaceDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(5))));
    public static final r9.c k = new r9.c("onDeviceFaceLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(59))));
    public static final r9.c l = new r9.c("onDeviceTextDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(6))));
    public static final r9.c m = new r9.c("onDeviceTextDetectionLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(79))));
    public static final r9.c n = new r9.c("onDeviceBarcodeDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(7))));
    public static final r9.c o = new r9.c("onDeviceBarcodeLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(58))));
    public static final r9.c p = new r9.c("onDeviceImageLabelCreateLogEvent", s3.c.h(i0.a.r(h0.class, new e0(48))));
    public static final r9.c q = new r9.c("onDeviceImageLabelLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(49))));
    public static final r9.c r = new r9.c("onDeviceImageLabelDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(18))));
    public static final r9.c s = new r9.c("onDeviceObjectCreateLogEvent", s3.c.h(i0.a.r(h0.class, new e0(26))));
    public static final r9.c t = new r9.c("onDeviceObjectLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(27))));
    public static final r9.c u = new r9.c("onDeviceObjectInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(28))));
    public static final r9.c v = new r9.c("onDevicePoseDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(44))));
    public static final r9.c w = new r9.c("onDeviceSegmentationLogEvent", s3.c.h(i0.a.r(h0.class, new e0(45))));
    public static final r9.c x = new r9.c("onDeviceSmartReplyLogEvent", s3.c.h(i0.a.r(h0.class, new e0(19))));
    public static final r9.c y = new r9.c("onDeviceLanguageIdentificationLogEvent", s3.c.h(i0.a.r(h0.class, new e0(21))));
    public static final r9.c z = new r9.c("onDeviceTranslationLogEvent", s3.c.h(i0.a.r(h0.class, new e0(22))));
    public static final r9.c A = new r9.c("cloudFaceDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(8))));
    public static final r9.c B = new r9.c("cloudCropHintDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(9))));
    public static final r9.c C = new r9.c("cloudDocumentTextDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(10))));
    public static final r9.c D = new r9.c("cloudImagePropertiesDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(11))));
    public static final r9.c E = new r9.c("cloudImageLabelDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(12))));
    public static final r9.c F = new r9.c("cloudLandmarkDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(13))));
    public static final r9.c G = new r9.c("cloudLogoDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(14))));
    public static final r9.c H = new r9.c("cloudSafeSearchDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(15))));
    public static final r9.c I = new r9.c("cloudTextDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(16))));
    public static final r9.c J = new r9.c("cloudWebSearchDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(17))));
    public static final r9.c K = new r9.c("automlImageLabelingCreateLogEvent", s3.c.h(i0.a.r(h0.class, new e0(23))));
    public static final r9.c L = new r9.c("automlImageLabelingLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(24))));
    public static final r9.c M = new r9.c("automlImageLabelingInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(25))));
    public static final r9.c N = new r9.c("isModelDownloadedLogEvent", s3.c.h(i0.a.r(h0.class, new e0(39))));
    public static final r9.c O = new r9.c("deleteModelLogEvent", s3.c.h(i0.a.r(h0.class, new e0(40))));
    public static final r9.c P = new r9.c("aggregatedAutomlImageLabelingInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(30))));
    public static final r9.c Q = new r9.c("aggregatedCustomModelInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(31))));
    public static final r9.c R = new r9.c("aggregatedOnDeviceFaceDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(32))));
    public static final r9.c S = new r9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(33))));
    public static final r9.c T = new r9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(34))));
    public static final r9.c U = new r9.c("aggregatedOnDeviceObjectInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(35))));
    public static final r9.c V = new r9.c("aggregatedOnDeviceTextDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(36))));
    public static final r9.c W = new r9.c("aggregatedOnDevicePoseDetectionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(46))));
    public static final r9.c X = new r9.c("aggregatedOnDeviceSegmentationLogEvent", s3.c.h(i0.a.r(h0.class, new e0(47))));
    public static final r9.c Y = new r9.c("pipelineAccelerationInferenceEvents", s3.c.h(i0.a.r(h0.class, new e0(69))));
    public static final r9.c Z = new r9.c("remoteConfigLogEvent", s3.c.h(i0.a.r(h0.class, new e0(42))));
    public static final r9.c a0 = new r9.c("inputImageConstructionLogEvent", s3.c.h(i0.a.r(h0.class, new e0(50))));
    public static final r9.c b0 = new r9.c("leakedHandleEvent", s3.c.h(i0.a.r(h0.class, new e0(51))));
    public static final r9.c c0 = new r9.c("cameraSourceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(52))));
    public static final r9.c d0 = new r9.c("imageLabelOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(53))));
    public static final r9.c e0 = new r9.c("languageIdentificationOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(54))));
    public static final r9.c f0 = new r9.c("faceDetectionOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(60))));
    public static final r9.c g0 = new r9.c("nlClassifierOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(55))));
    public static final r9.c h0 = new r9.c("nlClassifierClientLibraryLogEvent", s3.c.h(i0.a.r(h0.class, new e0(56))));
    public static final r9.c i0 = new r9.c("accelerationAllowlistLogEvent", s3.c.h(i0.a.r(h0.class, new e0(57))));
    public static final r9.c j0 = new r9.c("toxicityDetectionCreateEvent", s3.c.h(i0.a.r(h0.class, new e0(62))));
    public static final r9.c k0 = new r9.c("toxicityDetectionLoadEvent", s3.c.h(i0.a.r(h0.class, new e0(63))));
    public static final r9.c l0 = new r9.c("toxicityDetectionInferenceEvent", s3.c.h(i0.a.r(h0.class, new e0(64))));
    public static final r9.c m0 = new r9.c("barcodeDetectionOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(65))));
    public static final r9.c n0 = new r9.c("customImageLabelOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(66))));
    public static final r9.c o0 = new r9.c("codeScannerScanApiEvent", s3.c.h(i0.a.r(h0.class, new e0(67))));
    public static final r9.c p0 = new r9.c("codeScannerOptionalModuleEvent", s3.c.h(i0.a.r(h0.class, new e0(68))));
    public static final r9.c q0 = new r9.c("onDeviceExplicitContentCreateLogEvent", s3.c.h(i0.a.r(h0.class, new e0(70))));
    public static final r9.c r0 = new r9.c("onDeviceExplicitContentLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(71))));
    public static final r9.c s0 = new r9.c("onDeviceExplicitContentInferenceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(72))));
    public static final r9.c t0 = new r9.c("aggregatedOnDeviceExplicitContentLogEvent", s3.c.h(i0.a.r(h0.class, new e0(73))));
    public static final r9.c u0 = new r9.c("onDeviceSelfieFaceCreateLogEvent", s3.c.h(i0.a.r(h0.class, new e0(74))));
    public static final r9.c v0 = new r9.c("onDeviceSelfieFaceLoadLogEvent", s3.c.h(i0.a.r(h0.class, new e0(75))));
    public static final r9.c w0 = new r9.c("onDeviceSelfieFaceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(76))));
    public static final r9.c x0 = new r9.c("aggregatedOnDeviceSelfieFaceLogEvent", s3.c.h(i0.a.r(h0.class, new e0(77))));
    public static final r9.c y0 = new r9.c("smartReplyOptionalModuleLogEvent", s3.c.h(i0.a.r(h0.class, new e0(78))));

    @Override // r9.a
    public final void a(Object obj, Object obj2) {
        u7 u7Var = (u7) obj;
        r9.e eVar = (r9.e) obj2;
        eVar.a(b, u7Var.a);
        eVar.a(c, u7Var.b);
        eVar.a(d, null);
        eVar.a(e, u7Var.c);
        eVar.a(f, null);
        eVar.a(g, null);
        eVar.a(h, null);
        eVar.a(i, null);
        eVar.a(j, null);
        eVar.a(k, null);
        eVar.a(l, null);
        eVar.a(m, null);
        eVar.a(n, null);
        eVar.a(o, null);
        eVar.a(p, null);
        eVar.a(q, u7Var.d);
        eVar.a(r, u7Var.e);
        eVar.a(s, null);
        eVar.a(t, null);
        eVar.a(u, null);
        eVar.a(v, null);
        eVar.a(w, null);
        eVar.a(x, null);
        eVar.a(y, null);
        eVar.a(z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, u7Var.f);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(a0, null);
        eVar.a(b0, null);
        eVar.a(c0, null);
        eVar.a(d0, null);
        eVar.a(e0, null);
        eVar.a(f0, null);
        eVar.a(g0, null);
        eVar.a(h0, null);
        eVar.a(i0, null);
        eVar.a(j0, null);
        eVar.a(k0, null);
        eVar.a(l0, null);
        eVar.a(m0, null);
        eVar.a(n0, null);
        eVar.a(o0, null);
        eVar.a(p0, null);
        eVar.a(q0, null);
        eVar.a(r0, null);
        eVar.a(s0, null);
        eVar.a(t0, null);
        eVar.a(u0, null);
        eVar.a(v0, null);
        eVar.a(w0, null);
        eVar.a(x0, null);
        eVar.a(y0, null);
    }
}
