package h7;

/* compiled from: r8-map-id-818410c928e26989539d9c43666f59979e404aa44db880373fadfbe90836d366 */
/* loaded from: classes.dex */
public final class g3 implements r9.d {
    public static final g3 a = new g3();
    public static final r9.c b = new r9.c("systemInfo", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(1))));
    public static final r9.c c = new r9.c("eventName", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(2))));
    public static final r9.c d = new r9.c("isThickClient", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(37))));
    public static final r9.c e = new r9.c("clientType", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(61))));
    public static final r9.c f = new r9.c("modelDownloadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(3))));
    public static final r9.c g = new r9.c("customModelLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(20))));
    public static final r9.c h = new r9.c("customModelInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(4))));
    public static final r9.c i = new r9.c("customModelCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(29))));
    public static final r9.c j = new r9.c("onDeviceFaceDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(5))));
    public static final r9.c k = new r9.c("onDeviceFaceLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(59))));
    public static final r9.c l = new r9.c("onDeviceTextDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(6))));
    public static final r9.c m = new r9.c("onDeviceTextDetectionLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(79))));
    public static final r9.c n = new r9.c("onDeviceBarcodeDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(7))));
    public static final r9.c o = new r9.c("onDeviceBarcodeLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(58))));
    public static final r9.c p = new r9.c("onDeviceImageLabelCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(48))));
    public static final r9.c q = new r9.c("onDeviceImageLabelLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(49))));
    public static final r9.c r = new r9.c("onDeviceImageLabelDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(18))));
    public static final r9.c s = new r9.c("onDeviceObjectCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(26))));
    public static final r9.c t = new r9.c("onDeviceObjectLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(27))));
    public static final r9.c u = new r9.c("onDeviceObjectInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(28))));
    public static final r9.c v = new r9.c("onDevicePoseDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(44))));
    public static final r9.c w = new r9.c("onDeviceSegmentationLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(45))));
    public static final r9.c x = new r9.c("onDeviceSmartReplyLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(19))));
    public static final r9.c y = new r9.c("onDeviceLanguageIdentificationLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(21))));
    public static final r9.c z = new r9.c("onDeviceTranslationLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(22))));
    public static final r9.c A = new r9.c("cloudFaceDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(8))));
    public static final r9.c B = new r9.c("cloudCropHintDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(9))));
    public static final r9.c C = new r9.c("cloudDocumentTextDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(10))));
    public static final r9.c D = new r9.c("cloudImagePropertiesDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(11))));
    public static final r9.c E = new r9.c("cloudImageLabelDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(12))));
    public static final r9.c F = new r9.c("cloudLandmarkDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(13))));
    public static final r9.c G = new r9.c("cloudLogoDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(14))));
    public static final r9.c H = new r9.c("cloudSafeSearchDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(15))));
    public static final r9.c I = new r9.c("cloudTextDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(16))));
    public static final r9.c J = new r9.c("cloudWebSearchDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(17))));
    public static final r9.c K = new r9.c("automlImageLabelingCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(23))));
    public static final r9.c L = new r9.c("automlImageLabelingLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(24))));
    public static final r9.c M = new r9.c("automlImageLabelingInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(25))));
    public static final r9.c N = new r9.c("isModelDownloadedLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(39))));
    public static final r9.c O = new r9.c("deleteModelLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(40))));
    public static final r9.c P = new r9.c("aggregatedAutomlImageLabelingInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(30))));
    public static final r9.c Q = new r9.c("aggregatedCustomModelInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(31))));
    public static final r9.c R = new r9.c("aggregatedOnDeviceFaceDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(32))));
    public static final r9.c S = new r9.c("aggregatedOnDeviceBarcodeDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(33))));
    public static final r9.c T = new r9.c("aggregatedOnDeviceImageLabelDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(34))));
    public static final r9.c U = new r9.c("aggregatedOnDeviceObjectInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(35))));
    public static final r9.c V = new r9.c("aggregatedOnDeviceTextDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(36))));
    public static final r9.c W = new r9.c("aggregatedOnDevicePoseDetectionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(46))));
    public static final r9.c X = new r9.c("aggregatedOnDeviceSegmentationLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(47))));
    public static final r9.c Y = new r9.c("pipelineAccelerationInferenceEvents", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(69))));
    public static final r9.c Z = new r9.c("remoteConfigLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(42))));
    public static final r9.c a0 = new r9.c("inputImageConstructionLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(50))));
    public static final r9.c b0 = new r9.c("leakedHandleEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(51))));
    public static final r9.c c0 = new r9.c("cameraSourceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(52))));
    public static final r9.c d0 = new r9.c("imageLabelOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(53))));
    public static final r9.c e0 = new r9.c("languageIdentificationOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(54))));
    public static final r9.c f0 = new r9.c("faceDetectionOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(60))));
    public static final r9.c g0 = new r9.c("documentDetectionOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(85))));
    public static final r9.c h0 = new r9.c("documentCroppingOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(86))));
    public static final r9.c i0 = new r9.c("documentEnhancementOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(87))));
    public static final r9.c j0 = new r9.c("nlClassifierOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(55))));
    public static final r9.c k0 = new r9.c("nlClassifierClientLibraryLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(56))));
    public static final r9.c l0 = new r9.c("accelerationAllowlistLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(57))));
    public static final r9.c m0 = new r9.c("toxicityDetectionCreateEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(62))));
    public static final r9.c n0 = new r9.c("toxicityDetectionLoadEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(63))));
    public static final r9.c o0 = new r9.c("toxicityDetectionInferenceEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(64))));
    public static final r9.c p0 = new r9.c("barcodeDetectionOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(65))));
    public static final r9.c q0 = new r9.c("customImageLabelOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(66))));
    public static final r9.c r0 = new r9.c("codeScannerScanApiEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(67))));
    public static final r9.c s0 = new r9.c("codeScannerOptionalModuleEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(68))));
    public static final r9.c t0 = new r9.c("onDeviceExplicitContentCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(70))));
    public static final r9.c u0 = new r9.c("onDeviceExplicitContentLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(71))));
    public static final r9.c v0 = new r9.c("onDeviceExplicitContentInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(72))));
    public static final r9.c w0 = new r9.c("aggregatedOnDeviceExplicitContentLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(73))));
    public static final r9.c x0 = new r9.c("onDeviceFaceMeshCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(74))));
    public static final r9.c y0 = new r9.c("onDeviceFaceMeshLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(75))));
    public static final r9.c z0 = new r9.c("onDeviceFaceMeshLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(76))));
    public static final r9.c A0 = new r9.c("aggregatedOnDeviceFaceMeshLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(77))));
    public static final r9.c B0 = new r9.c("smartReplyOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(78))));
    public static final r9.c C0 = new r9.c("textDetectionOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(80))));
    public static final r9.c D0 = new r9.c("onDeviceImageQualityAnalysisCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(81))));
    public static final r9.c E0 = new r9.c("onDeviceImageQualityAnalysisLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(82))));
    public static final r9.c F0 = new r9.c("onDeviceImageQualityAnalysisLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(83))));
    public static final r9.c G0 = new r9.c("aggregatedOnDeviceImageQualityAnalysisLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(84))));
    public static final r9.c H0 = new r9.c("imageQualityAnalysisOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(88))));
    public static final r9.c I0 = new r9.c("imageCaptioningOptionalModuleLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(89))));
    public static final r9.c J0 = new r9.c("onDeviceImageCaptioningCreateLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(90))));
    public static final r9.c K0 = new r9.c("onDeviceImageCaptioningLoadLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(91))));
    public static final r9.c L0 = new r9.c("onDeviceImageCaptioningInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(92))));
    public static final r9.c M0 = new r9.c("aggregatedOnDeviceImageCaptioningInferenceLogEvent", s3.c.h(com.google.android.recaptcha.internal.a.r(d.class, new a(93))));

    @Override // r9.a
    public final void a(Object obj, Object obj2) {
        j7 j7Var = (j7) obj;
        r9.e eVar = (r9.e) obj2;
        eVar.a(b, j7Var.a);
        eVar.a(c, j7Var.b);
        eVar.a(d, null);
        eVar.a(e, null);
        eVar.a(f, null);
        eVar.a(g, null);
        eVar.a(h, null);
        eVar.a(i, null);
        eVar.a(j, null);
        eVar.a(k, null);
        eVar.a(l, null);
        eVar.a(m, null);
        eVar.a(n, null);
        eVar.a(o, null);
        eVar.a(p, null);
        eVar.a(q, null);
        eVar.a(r, null);
        eVar.a(s, null);
        eVar.a(t, null);
        eVar.a(u, null);
        eVar.a(v, null);
        eVar.a(w, null);
        eVar.a(x, null);
        eVar.a(y, null);
        eVar.a(z, null);
        eVar.a(A, null);
        eVar.a(B, null);
        eVar.a(C, null);
        eVar.a(D, null);
        eVar.a(E, null);
        eVar.a(F, null);
        eVar.a(G, null);
        eVar.a(H, null);
        eVar.a(I, null);
        eVar.a(J, null);
        eVar.a(K, null);
        eVar.a(L, null);
        eVar.a(M, null);
        eVar.a(N, null);
        eVar.a(O, null);
        eVar.a(P, null);
        eVar.a(Q, null);
        eVar.a(R, null);
        eVar.a(S, null);
        eVar.a(T, null);
        eVar.a(U, null);
        eVar.a(V, null);
        eVar.a(W, null);
        eVar.a(X, null);
        eVar.a(Y, null);
        eVar.a(Z, null);
        eVar.a(a0, j7Var.c);
        eVar.a(b0, null);
        eVar.a(c0, null);
        eVar.a(d0, null);
        eVar.a(e0, null);
        eVar.a(f0, null);
        eVar.a(g0, null);
        eVar.a(h0, null);
        eVar.a(i0, null);
        eVar.a(j0, null);
        eVar.a(k0, null);
        eVar.a(l0, null);
        eVar.a(m0, null);
        eVar.a(n0, null);
        eVar.a(o0, null);
        eVar.a(p0, null);
        eVar.a(q0, null);
        eVar.a(r0, null);
        eVar.a(s0, null);
        eVar.a(t0, null);
        eVar.a(u0, null);
        eVar.a(v0, null);
        eVar.a(w0, null);
        eVar.a(x0, null);
        eVar.a(y0, null);
        eVar.a(z0, null);
        eVar.a(A0, null);
        eVar.a(B0, null);
        eVar.a(C0, null);
        eVar.a(D0, null);
        eVar.a(E0, null);
        eVar.a(F0, null);
        eVar.a(G0, null);
        eVar.a(H0, null);
        eVar.a(I0, null);
        eVar.a(J0, null);
        eVar.a(K0, null);
        eVar.a(L0, null);
        eVar.a(M0, null);
    }
}
